export default {
  HANDLE_GET_COORDINATES: "HANDLE_GET_COORDINATES",
  HANDLE_GET_USING_DATES: "HANDLE_GET_USING_DATES",
  GET_COORDINATES: "GET_COORDINATES",
  GET_USING_DATES: "GET_USING_DATES",
};
