export default {
  HANDLE_START_TRACKING: "HANDLE_START_TRACKING",
  HANDLE_STOP_TRACKING: "HANDLE_STOP_TRACKING",
  GET_CURRENT_COORDINATES: "GET_CURRENT_COORDINATES",
  PUSH_COORDINATE: "PUTH_COORDINATES",
  FAIL_TRACKING: "FAIL_TRACKING",
  READY: "READY",
};
